### ISSUE TITLE
About Pose Keypoints

### ISSUE THREAD

**Issue by SherlockHolmes221** [bobwan1995/PMFNet#11]
Which github repository did you use to generate the person pose keypoints?
I already know that you use "Multi-Context Attention for Human Pose Estimation" but I cannot find a appropriate github repository in pytorch

**Comment by desenzhou** [comment]
We use the cod [](https://github.com/GengDavid/pytorch-cpn) to generate person pose.

**Comment by desenzhou** [comment]
We use the code [cpn](https://github.com/GengDavid/pytorch-cpn) to generate person pose.

**Comment by SherlockHolmes221** [comment]
Thanks a lot!
