### ISSUE TITLE
Reproduce mAP in V-COCO

### ISSUE THREAD

**Issue by tengyu-liu** [bobwan1995/PMFNet#12]
In your paper (Table 4) you mentioned that your model achieves 53.0 mAP on v-coco validation set. Is there a way to reproduce this number with your code?

**Comment by bobwan1995** [comment]
You can train on trainset and validate on valset.

**Comment by tengyu-liu** [comment]
Is there code available for evaluation?

**Comment by tengyu-liu** [comment]
I've been reading through your code but haven't been able to spot the use of vsrl_eval.py from [the official v-coco repository](https://github.com/s-gupta/v-coco)

**Comment by bobwan1995** [comment]
In lib/datasets/vcoco_json.py I copy the same code from vsrl_eval.py in vcoco repo, please check it agian. You'd better run our code from scratch and you will get familiar with the project. Thank you for your interests in our work!

**Comment by BestSongEver** [comment]
I'm trying to train the code to reproduce mAP in V-COCO.
But i got the Error while training.

[Step 2801 / 6000]	2020-02-28 16:31:36
	loss: 0.072079, lr: 0.080000 time: 1.499334, eta: 1:19:57
	accuracy_interaction_affinity: 0.627009, accuracy_interaction_cls: 0.985619	loss_hoi_interaction_action: 0.044325, loss_hoi_interaction_affinity: 0.025307
INFO train_net_step.py: 608: Decay the learning on step 3000
INFO net.py: 198: Changing learning rate 0.080000 -> 0.008000
INFO net.py: 227: Scaling update history by 0.100000 (new lr / old lr)
Traceback (most recent call last):
  File "tools/train_net_step.py", line 752, in <module>
    main()
  File "tools/train_net_step.py", line 551, in main
    train_val(maskRCNN, args, optimizer, lr, dataloader, train_size, output_dir, tblogger)
  File "tools/train_net_step.py", line 610, in train_val
    net_utils.update_learning_rate(optimizer, lr, lr_new)
  File "/userhome/project/PMFNet/lib/utils/net.py", line 213, in update_learning_rate
    _CorrectMomentum(optimizer, param_keys, new_lr / cur_lr)
  File "/userhome/project/PMFNet/lib/utils/net.py", line 229, in _CorrectMomentum
    optimizer.state[p_key]['momentum_buffer'] *= correction
KeyError: 'momentum_buffer'

I kept everything the same but only changed one parameter (--nw 2 ). Could you please offer some help? @bobwan1995 @tengyu-liu
