### ISSUE TITLE
PMFNet of HICO

### ISSUE THREAD

**Issue by kaenkogashi** [bobwan1995/PMFNet#13]
Can you upload HICO reference code?

**Comment by BestSongEver** [comment]
Thanx for ur great job. @bobwan1995 
I'm also interested in testing the code on the bigger banchmark HICO. 
Could u please uadate the related code and pre-trained models?

**Comment by bobwan1995** [comment]
I build another project for HICO and I need to merge them. It may take some time because I'm busy these days. I will make my best efforts to finish it asap.
