### ISSUE TITLE
Add Data Augmentation

### ISSUE THREAD

**Issue by yichen928** [bobwan1995/PMFNet#14]
Hello, thank you for this excellent work.
I try to add a data augmentation method to your work but I find your data loader is a little complex. Can you tell me how you preprocess and load the v-coco data? And if I want to process the loaded image and its annotation simultaneously online, are there any convenient ways to modify your code?
Thank you very much.

**Comment by youngfly11** [comment]
You should have more patience to read our codes carefully. All you need are included in this repo.

**Comment by yichen928** [comment]
Thank you, and I will read it again more carefully.
