### ISSUE TITLE
Question about computing the affinity score

### ISSUE THREAD

**Issue by BestSongEver** [bobwan1995/PMFNet#15]
Thanx for ur great job. @bobwan1995 @desenzhou 
As shown in ur paper, u compute the affinity score using the Holistic Feature only.
But, as i read from lib/modeling/hoi.py, u compute the affinity score (i.e. interaction_affinity_score in the code) using both Holistic Feature and Zoom-in Feature, which is same as computing local relation score (i.e. interaction_action_score in the code)?  
Please see lib/modeling/hoi.py in line 347-349

I am so confused that I couldn't eat my meal. Does it mean using both Holistic Feature and Zoom-in Feature in computing  the affinity score is better than Holistic Feature only?
Waiting for reply. Thanx!

**Comment by bobwan1995** [comment]
You are very meticulous. Actually the performance is close when we use holistic or holistic+local features to predict binary scores. This code is an initial version where we use holistic+local, I will revise it and give a new ckpt later (maybe after I get back to school). In conclusion, there is nearly no difference whether to use holistic or holistic+local features to predict binary scores, and you can try it by yourself. We choose to only use holistic features just for simplification. Thank you!

**Comment by BestSongEver** [comment]
I got it! Thanx again.
Looking forward to your HICO code, by the way. 
I can eat my hamburger in peace now. Zhen Xiang!
