### ISSUE TITLE
Error while Training&Testing the code

### ISSUE THREAD

**Issue by BestSongEver** [bobwan1995/PMFNet#16]
I'm trying to train the code to reproduce mAP in V-COCO.
But i got the Error while training.

[Step 2801 / 6000]	2020-02-28 16:31:36
loss: 0.072079, lr: 0.080000 time: 1.499334, eta: 1:19:57
accuracy_interaction_affinity: 0.627009, accuracy_interaction_cls: 0.985619	loss_hoi_interaction_action: 0.044325, loss_hoi_interaction_affinity: 0.025307
INFO train_net_step.py: 608: Decay the learning on step 3000
INFO net.py: 198: Changing learning rate 0.080000 -> 0.008000
INFO net.py: 227: Scaling update history by 0.100000 (new lr / old lr)
Traceback (most recent call last):
File "tools/train_net_step.py", line 752, in 
main()
File "tools/train_net_step.py", line 551, in main
train_val(maskRCNN, args, optimizer, lr, dataloader, train_size, output_dir, tblogger)
File "tools/train_net_step.py", line 610, in train_val
net_utils.update_learning_rate(optimizer, lr, lr_new)
File "/userhome/project/PMFNet/lib/utils/net.py", line 213, in update_learning_rate
_CorrectMomentum(optimizer, param_keys, new_lr / cur_lr)
File "/userhome/project/PMFNet/lib/utils/net.py", line 229, in _CorrectMomentum
optimizer.state[p_key]['momentum_buffer'] *= correction
KeyError: 'momentum_buffer'

I kept everything the same but only changed one parameter (--nw 2 ). Could you please offer some help?  Thanx so much. @bobwan1995 @tengyu-liu

**Comment by Kebii** [comment]
I ran into the same problem with the SGD optimizer. Can I reproduce the same mAP by Adam optimizer? @bobwan1995

**Comment by BestSongEver** [comment]
Did u solve the problem of SGD optimizer?
If so, could u please share me ur code? Thanx!  @Kebii

**Comment by Kebii** [comment]
I just added an 'if' to avoid this error, I don't know if I can get the ideal result. 
I tried using the Adam optimizer to train the network, but it didn't work.

------------------------------------------net.py------------------------------------------------------
def _CorrectMomentum(optimizer, param_keys, correction):
    logger.info('Scaling update history by %.6f (new lr / old lr)', correction)
    for p_key in param_keys:
        if "momentum_buffer" in optimizer.state[p_key].keys():
            optimizer.state[p_key]['momentum_buffer'] *= correction

**Comment by bobwan1995** [comment]
do you use correct pytorch version (0.4.1)?

**Comment by Kebii** [comment]
> do you use correct pytorch version (0.4.1)?

Thanks for your reply!
 I use the correct version 0.4.1 of pytorch.

**Comment by BestSongEver** [comment]
I am using the correct version 0.4.1 of pytorch too.
I've been using @Kebii 's solution to train the code, which looks working still now.
Thank both of you. @Kebii @bobwan1995 
U may close the issue if u think the problem is solved. @bobwan1995

**Comment by BestSongEver** [comment]
I'm glad I finished the training
But when I'm going to test my model, it goes as follows：
RuntimeError: cuda runtime error (2) : out of memory 

Too bad. I wonder if there is a way to fix it.
