### ISSUE TITLE
What's the difference between ‘vcoco_test_ap_3’ and ‘vcoco_test_ap_13’？

### ISSUE THREAD

**Issue by Kebii** [bobwan1995/PMFNet#19]
What do the numbers 3 and 13 mean in the output result? @bobwan1995 Thanks!

**Comment by youngfly11** [comment]
3 denotes the results without affinity score.  13 denote the results with affinity score

**Comment by Kebii** [comment]
> 3 denotes the results without affinity score. 13 denote the results with affinity score

thanks！
