### ISSUE TITLE
where can l get the paper

### ISSUE THREAD

**Issue by qqqlz** [bobwan1995/PMFNet#2]
Hello,
I want to know where can l get the paper?

**Comment by bobwan1995** [comment]
Thank you for your interest in our paper. I've just committed it to Arxiv and it will be available in 2-3 days.

**Comment by bobwan1995** [comment]
Available at _https://arxiv.org/pdf/1909.08453.pdf_

**Comment by qqqlz** [comment]
Hello,
I also want to know when can I get the code?

**Comment by bobwan1995** [comment]
We'll release codes soon, maybe in one or two weeks.

**Comment by tlecouffe** [comment]
> We'll release codes soon, maybe in one or two weeks.

Hi!  Any updates on the code release?
