### ISSUE TITLE
affinity_mat when testing

### ISSUE THREAD

**Issue by SherlockHolmes221** [bobwan1995/PMFNet#20]
I found that you loaded an affinity mat when testing but did't use it.  Dose the affinity_mat save the best affinity score and useful for testing?
Looking forward to your reply.

**Comment by youngfly11** [comment]
For simplicity, our initial experiments used the saved affinity score to evaluate the final ap. But our model can be trained in an end-to-end manner. You can try it by yourself

**Comment by SherlockHolmes221** [comment]
Thanks a lot
