### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by SherlockHolmes221** [bobwan1995/PMFNet#25]
How I can get the training data of HICO?
you said that the data come from iCAN, but I found the training data of V-COCO dataset is different from iCAN(test data are the same), so how did you get the training data of HICO and V-COCO?
Thanks

**Comment by BestSongEver** [comment]
Thanx for ur great job. @bobwan1995
I'm going to cite ur work into my paper. But befort that, I have to make more ablation results on HICO with ur project.
Could u please update the related HICO code and pre-trained models/ training data (e.g., baidu drive link)?
Thanx!

Did u get the HICO code and data? It will be very helpful if u can share it to me (e.g., maybe a drive link). Many thanks! @SherlockHolmes221

**Comment by SherlockHolmes221** [comment]
No, I create a HICO data by myself using Detectron
