### ISSUE TITLE
lose file

### ISSUE THREAD

**Issue by hutao568** [bobwan1995/PMFNet#27]
nms的src下面少了nms_cuda.c文件

**Comment by suzhan-123** [comment]
我也出现了一样的问题，以及下方tacceback是出现了distutils.errors.DistutilsExecError: command '/usr/local/miniconda3/envs/dl/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1，请问你解决这个问题了吗？

**Comment by hutao568** [comment]
> 我也出现了一样的问题，以及下方tacceback是出现了distutils.errors.DistutilsExecError: command '/usr/local/miniconda3/envs/dl/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1，请问你解决这个问题了吗？

解决了，从faster RCNN里面拉一个就行

**Comment by WinstonDeng** [comment]
@hutao568 hi, 可以给我分享一下 num_cuda.c 吗（842237857@qq.com）？我没有在其他地方找到相关文件 : )

**Comment by hutao568** [comment]
https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/nms/src/nms_cuda.c
