### ISSUE TITLE
Unable to access pan.baidu

### ISSUE THREAD

**Issue by seyedsajadashrafi** [bobwan1995/PMFNet#28]
Thank you for releasing codes. I am unable to access the annotations and detection/keypoint proposals that are saved in pan.baidu. How can I access these files?

**Comment by finngaida** [comment]
I have the same problem, did you manage to access it?

**Comment by bobwan1995** [comment]
Sorry, I will put it to google driver soon.

**Comment by bobwan1995** [comment]
I've put it to Google Drive. Hope you have a good time!

**Comment by finngaida** [comment]
Thanks for the fast response! This helps a lot
