### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Gaoyiminggithub** [bobwan1995/PMFNet#5]
Hi, 
thanks for your great work.
I wonder in the paper, the map results on VCOCO dataset are evaluated as Average Role [scenario_2 or 1] or Average Role [scenario_2 or 1] omitting the action "point"?
Thanks very much!

**Comment by bobwan1995** [comment]
The short answer is: the evaluation matrix we report is AP_role in scenario 1 that omitting the action "point", which is exactly the same with prior works.
